/**
 * Monthly finance-lease prices harvested from the old vansales.com product pages.
 * Keyed by new-vans slug. Values are ex-VAT p/m prices in whole pounds.
 * Source: ~/vansales-seed/content/product-*.md → first "### £X" occurrence.
 */
export const NEW_VAN_PRICES: Record<string, number> = {
  "citroen-berlingo-crew-cab": 349,
  "citroen-berlingo-enterprise": 350,
  "citroen-berlingo-lease": 349,
  "citroen-dispatch-crew-cab": 349,
  "citroen-dispatch-lease": 359,
  "citroen-e-berlingo": 349,
  "citroen-relay-lease": 449,
  "citroen-relay-tipper": 369,
  "fiat-doblo-lease": 350,
  "fiat-ducato-lease": 449,
  "fiat-ducato-luton": 499,
  "fiat-scudo-crew-cab": 349,
  "fiat-scudo-lease": 300,
  "ford-e-transit-courier": 599,
  "ford-e-transit-custom": 349,
  "ford-e-transit": 279,
  "ford-ranger-lease": 599,
  "ford-ranger-phev": 349,
  "ford-tourneo-custom-minibus-lease": 599,
  "ford-tourneo-custom": 599,
  "ford-transit-connect-lease": 350,
  "ford-transit-connect-phev": 599,
  "ford-transit-courier-lease": 349,
  "ford-transit-custom-automatic": 379,
  "ford-transit-custom-crew-cab-lease": 349,
  "ford-transit-custom-dciv-phev": 279,
  "ford-transit-custom-lease": 379,
  "ford-transit-custom-limited": 379,
  "ford-transit-custom-phev": 599,
  "ford-transit-custom-sport": 300,
  "ford-transit-double-cab": 349,
  "ford-transit-lease": 599,
  "ford-transit-luton": 599,
  "ford-transit-tipper": 599,
  "iveco-daily-lease": 369,
  "iveco-daily-luton-van": 499,
  "iveco-daily-minibus": 599,
  "iveco-daily-tipper": 499,
  "mercedes-citan-lease": 349,
  "mercedes-luton-van": 499,
  "mercedes-sprinter-lease": 350,
  "mercedes-sprinter-luton-rental": 260,
  "mercedes-sprinter-tipper": 499,
  "mercedes-vito-crew-cab-lease": 349,
  "new-renault-master": 499,
  "new-vauxhall-movano": 299,
  "nissan-interstar-lease": 499,
  "nissan-interstar-tipper": 369,
  "nissan-primastar-lease": 499,
  "nissan-townstar-lease": 349,
  "peugeot-boxer-lease": 249,
  "peugeot-expert-lease": 379,
  "peugeot-partner-lease": 349,
  "renault-kangoo-lease": 350,
  "renault-master-lease": 499,
  "renault-master-low-loader": 499,
  "renault-master-luton": 499,
  "renault-trafic-crew-cab-lease": 349,
  "renault-trafic-lease": 499,
  "toyota-hilux-lease": 599,
  "toyota-proace-city-lease": 349,
  "toyota-proace-crew-cab": 349,
  "toyota-proace-lease": 349,
  "vauxhall-combi-lease": 349,
  "vauxhall-vivaro-lease": 299,
  "vauxhall-vivaro-medium-van": 300,
  "vauxhall-vivaro-prime": 300,
  "vw-caddy-lease": 349,
  "vw-crafter-lease": 449,
  "vw-crafter-luton": 499,
  "vw-crafter-tipper": 499,
  "vw-transporter-kombi-lease": 349,
  "vw-transporter-lease": 379,
  "vw-amarok-lease": 599,
};

export function getNewVanPrice(slug: string): number | null {
  return NEW_VAN_PRICES[slug] ?? null;
}
