// AUTO-GENERATED by scripts/generate-model-content.mjs — do not edit by hand.
// Source: read-only harvest of vansales.com (~/vansales-seed), sanitised:
// malware spam stripped, ALL outbound links removed, WP chrome dropped.
// Verified: 0 spam links / 0 residual URLs in the copy below.

export interface ModelContent {
  make: string;
  makeSlug: string;
  model: string;
  modelSlug: string;
  title: string;
  intro: string[];
  hero: string | null;
  heroAlt: string | null;
  sourceUrl: string;
  sourceType: "product" | "models" | "generated";
}

export const MODEL_CONTENT: Record<string, ModelContent> = {
  "volkswagen/transporter": {
    "make": "Volkswagen",
    "makeSlug": "volkswagen",
    "model": "Transporter",
    "modelSlug": "transporter",
    "title": "Volkswagen Transporter",
    "intro": [
      "VW Transporter lease deals give you some great financial benefits. Your monthly payments stay lower because you can push part of the van’s cost to the end of your contract. The cost breaks down into monthly payments you can easily manage for 3-5 years. The VW Transporter lease to buy option adds extra flexibility at the end of your term. You can keep the van by paying the final balloon payment, trade it in for a new vehicle, or spread the final amount over 12-60 months.",
      "This piece covers everything about VW Transporter leasing that you should know before signing your agreement. We’ll help you understand how leasing works and show you the best deals you can find right now.",
      "VW Transporter leasing works like a rental deal that lets you drive a Volkswagen van without buying it. This setup gives you plenty of flexibility whether you need it for personal use or business, and you’ll get access to newer vehicles without dealing with ownership hassles.",
      "The main difference between leasing and buying comes down to who owns the van. Leasing means you’re renting the VW Transporter for a set time, and you’ll pay less each month compared to buying it. Once your agreement ends, you just give the van back. Buying means the van becomes yours after you’ve paid everything off."
    ],
    "hero": "/media/models/volkswagen-transporter.png",
    "heroAlt": "VW Transporter Sportline Black Edition for Sale Today",
    "sourceUrl": "https://www.vansales.com/product/vw-transporter-lease/",
    "sourceType": "product"
  },
  "volkswagen/transporter-kombi": {
    "make": "Volkswagen",
    "makeSlug": "volkswagen",
    "model": "Transporter Kombi",
    "modelSlug": "transporter-kombi",
    "title": "Volkswagen Transporter Kombi",
    "intro": [
      "The pricing spans from £299 monthly for the e-Transporter Panel Van to £478.46 (VAT included) for T30 SWB diesel models. Your VW Transporter Kombi lease agreement needs an original rental payment that ranges between £1,000 and £2,691 based on your contract terms.",
      "The VW Transporter Kombi lease becomes even more appealing with its 37% residual value after three years. This strong value retention shapes your long-term lease deals and helps you save money. The vehicle offers impressive utility with payload capacities up to 1304kg, which makes it a smart business investment.",
      "This piece will show you the exact payments, savings, and unexpected costs you might face after six months with your leased Transporter. We’ve studied countless contracts to give you the real picture of VW Transporter lease deals in 2025.",
      "The new seventh-generation VW Transporter Kombi brings a complete range of specifications that affect your lease costs. VW partnered with Ford Transit Custom to develop this crew van that lives up to Volkswagen’s reputation of mixing practicality with performance."
    ],
    "hero": "/media/models/volkswagen-transporter-kombi.webp",
    "heroAlt": "VW Transporter Kombi Lease",
    "sourceUrl": "https://www.vansales.com/product/vw-transporter-kombi-lease/",
    "sourceType": "product"
  },
  "volkswagen/caddy": {
    "make": "Volkswagen",
    "makeSlug": "volkswagen",
    "model": "Caddy",
    "modelSlug": "caddy",
    "title": "Volkswagen Caddy",
    "intro": [
      "The versatile van delivers great value with its 711kg payload capacity and fuel economy reaching 61.4 mpg. Our extensive research into VW Caddy lease deals shows why leasing could be a smarter financial choice for your business or family in 2025. Let us compare the costs, walk through your options, and help you decide if a lease fits your needs better.",
      "The numbers tell a compelling story about why leasing a VW Caddy makes financial sense. Business Contract Hire lets you get these commercial vehicles without putting down a huge amount of money upfront.",
      "Business Contract Hire costs nowhere near as much to start with compared to buying outright. The Caddy Cargo Commerce needs just £1,854 as your original rental, instead of the full £25,415 on-the-road price (excluding VAT). Your monthly payments stay fixed – usually around £309 for a 3-year, 10,000-mile annual agreement. This makes your budget planning and financial forecasting much easier.",
      "The lease deals often come with great manufacturer discounts and fixed-price servicing plans. To cite an instance, you can add two services for just £199 (excluding VAT), making your agreement more economical."
    ],
    "hero": "/media/models/volkswagen-caddy.webp",
    "heroAlt": "VW Caddy For Sale",
    "sourceUrl": "https://www.vansales.com/product/vw-caddy-lease/",
    "sourceType": "product"
  },
  "volkswagen/crafter": {
    "make": "Volkswagen",
    "makeSlug": "volkswagen",
    "model": "Crafter",
    "modelSlug": "crafter",
    "title": "Volkswagen Crafter",
    "intro": [
      "The standard VW Crafter Lease gives you a massive 4,300mm load length with 14.4 cubic meters of space while still carrying up to 1,200kg depending on your engine choice. Your business needs even more room? The LWB Maxi version with super high roof delivers an enormous 18.4 cubic meters of capacity.",
      "What makes this van special is how it balances size with efficiency. The Crafter achieves combined fuel consumption as low as 34mpg with CO2 outputs from just 217g/km. These numbers matter when you’re running a business and watching every penny on fuel costs.",
      "VW offers 8 different Crafter models to choose from. Monthly lease payments start at £359.96 for the Crafter Cr35 Lwb Fwd and go up to £436.35 for the Crafter Cr35 Lwb 4Motion. The mid-range Commerce Plus high roof panel van starts at £44,500 with monthly rentals of £559.",
      "The Crafter’s versatility shows in the details. You can fit four to six Euro pallets depending on the wheelbase you choose. Euro 6 compliant 2.0L diesel engines power every model, giving you the clean emissions standards that matter for city access."
    ],
    "hero": "/media/models/volkswagen-crafter.webp",
    "heroAlt": "VW Crafter For Sale",
    "sourceUrl": "https://www.vansales.com/product/vw-crafter-lease/",
    "sourceType": "product"
  },
  "volkswagen/amarok": {
    "make": "Volkswagen",
    "makeSlug": "volkswagen",
    "model": "Amarok",
    "modelSlug": "amarok",
    "title": "Volkswagen Amarok",
    "intro": [
      "I tested models of all trim levels – Life, Style, PanAmericana, and Aventura. The truck’s 5-star NCAP safety rating and 90% child occupant protection score really stood out. Monthly lease payments start at £232.58, but I managed to get an even better deal.",
      "Let me show you how I saved £4,500 on my Amarok lease using some hidden tactics and perfect timing. These tips could help you save money whether you want the 170hp diesel engine or the beefier 240 PS version.",
      "The hunt for the perfect VW Amarok lease deal needed patience, but it paid off big time. After looking through countless offers, I found that there was a hidden deal that saved me £4,500 – here’s the full story of how it happened.",
      "The first VW Amarok lease quotes I received lined up with what everyone else was paying in the market. Most dealers offered the Amarok Life at £399 per month on a 48-month contract hire agreement with 10,000 miles each year and an original rental of £3,591. Other quotes ranged from £365.83 excluding VAT monthly to £386.43 per month for business leases."
    ],
    "hero": "/media/models/volkswagen-amarok.webp",
    "heroAlt": "VW Amarok For Sale",
    "sourceUrl": "https://www.vansales.com/product/vw-amarok-lease/",
    "sourceType": "product"
  },
  "ford/transit-custom": {
    "make": "Ford",
    "makeSlug": "ford",
    "model": "Transit Custom",
    "modelSlug": "transit-custom",
    "title": "Ford Transit Custom",
    "intro": [
      "Whether you’re running a small delivery service or managing a large fleet, choosing between various leasing options can feel overwhelming. From standard vans to crew cabs and double cab variants, each configuration serves different business needs while offering unique financial advantages. See all Ford Transit Custom for sale",
      "Additionally, with flexible payment terms, tax benefits, and maintenance packages available, leasing a Transit Custom could be more cost-effective than outright purchase. No-deposit options and business-specific deals make these versatile vans accessible to companies of all sizes.",
      "This comprehensive guide breaks down everything you need to know about Ford Transit Custom leasing – from current deals and financing options to model variations and customization possibilities. Let’s explore how to secure the best lease agreement for your specific requirements. See all Ford Van Leasing",
      "The Ford Transit Custom stands at the heart of Ford’s commercial vehicle lineup, sitting between the larger Transit and smaller Transit Connect models. As Ford’s medium-sized van offering, it has established itself as the UK’s best-selling commercial vehicle, appealing to businesses seeking versatility and dependability from their lease agreements. See all Ford Van Lease deals"
    ],
    "hero": "/media/models/ford-transit-custom.png",
    "heroAlt": "Transit Custom Crew Cab",
    "sourceUrl": "https://www.vansales.com/product/ford-transit-custom-lease/",
    "sourceType": "product"
  },
  "ford/transit": {
    "make": "Ford",
    "makeSlug": "ford",
    "model": "Transit",
    "modelSlug": "transit",
    "title": "Ford Transit",
    "intro": [
      "Looking at a Ford Transit lease price requires understanding costs beyond the advertised monthly payments. The real cost breakdown shows why the advertised price rarely matches your final payment.",
      "Ford Transit lease offers showcase attractive monthly payments that represent only a portion of your total financial commitment. These monthly figures show the vehicle’s depreciation over your lease term plus interest.",
      "The original Ford Transit lease price calculation takes the difference between the vehicle’s current value and its expected lease-end value (residual value). This amount gets divided by your contract months. The final amount includes interest charges (or “lease factors”).",
      "The total lease cost includes many more elements like original rental payments (usually 3-12 months upfront), servicing packages, and various fees. A Transit advertised at £223 monthly could cost you over £15,000 through a typical 48-month contract."
    ],
    "hero": "/media/models/ford-transit.webp",
    "heroAlt": "Ford Transit Vans For Sale",
    "sourceUrl": "https://www.vansales.com/product/ford-transit-lease/",
    "sourceType": "product"
  },
  "ford/transit-connect": {
    "make": "Ford",
    "makeSlug": "ford",
    "model": "Transit Connect",
    "modelSlug": "transit-connect",
    "title": "Ford Transit Connect",
    "intro": [
      "Indeed, the Transit Connect’s versatile size, impressive fuel economy, and modern features make it a compelling choice for businesses. However, navigating through various lease deals, understanding tax implications, and selecting the right contract type can feel overwhelming.",
      "From business contract hire to finance lease agreements, each option comes with its own set of advantages and considerations. The right choice depends on your specific business requirements, budget constraints, and long-term goals.",
      "This comprehensive guide breaks down everything you need to know about leasing a Ford Transit Connect in the UK – from understanding different lease types to negotiating the best deals and maximizing tax benefits for your business.",
      "The Ford Transit Connect stands as a versatile workhorse in the commercial vehicle segment, offering an impressive balance of capacity, efficiency, and technology. Before committing to a Ford Transit Connect lease, understanding its full capabilities can help you select the most suitable configuration for your business needs."
    ],
    "hero": "/media/models/ford-transit-connect.webp",
    "heroAlt": "Ford Connect Vans For Sale",
    "sourceUrl": "https://www.vansales.com/product/ford-transit-connect-lease/",
    "sourceType": "product"
  },
  "ford/transit-courier": {
    "make": "Ford",
    "makeSlug": "ford",
    "model": "Transit Courier",
    "modelSlug": "transit-courier",
    "title": "Ford Transit Courier",
    "intro": [
      "Before diving into leasing details, let’s take a closer look at what makes the Ford Transit Courier stand out in the UK van market. This compact van packs a punch with its impressive specifications:",
      "Dimensions: 4,163 mm length and 1,835 mm width - Load capacity: 2.3 cubic meters - Maximum payload: 660 kg - Engine options: 1.0L EcoBoost petrol (100 PS) and 1.5L EcoBlue diesel (75 PS and 100 PS) - Fuel economy: Up to 50 mpg for petrol and 60 mpg for diesel variants - Safety: Euro NCAP 4-star rating",
      "The Transit Courier also boasts advanced features like the SYNC 3 infotainment system, lane-keeping assist, and automatic emergency braking. These attributes make it an ideal choice for businesses operating in urban environments or those requiring a nimble yet capable vehicle.",
      "Ford Transit Courier van leasing offers flexibility and financial advantages for small to medium enterprises. Here’s why leasing might be the smart choice for your business:"
    ],
    "hero": "/media/models/ford-transit-courier.webp",
    "heroAlt": "Ford Transit Custom Courier",
    "sourceUrl": "https://www.vansales.com/product/ford-transit-courier-lease/",
    "sourceType": "product"
  },
  "ford/ranger": {
    "make": "Ford",
    "makeSlug": "ford",
    "model": "Ranger",
    "modelSlug": "ranger",
    "title": "Ford Ranger",
    "intro": [
      "The Toyota Hilux and Isuzu D-Max remain strong competitors, but the Ranger’s lease deals are becoming more appealing. The 2025 lineup caters to every need. Buyers can choose between the practical XL trim and the high-performance Raptor that comes with a powerful 3.0-litre EcoBoost engine delivering 292 PS.",
      "Let us help you understand these price changes and get into the best deals available for different trim levels. This information will help you make a better decision about your next vehicle.",
      "Market forces have pushed Ford Ranger lease prices down in 2025. This price drop comes from careful planning, economic changes, and shifting customer priorities. Let’s get into the main reasons behind this great news for pickup fans.",
      "The automotive industry’s supply chain problems since 2020 have finally settled down. Ford began a mission to rebuild its Ranger manufacturing process, which led to big cost savings that customers now see in cheaper lease options."
    ],
    "hero": "/media/models/ford-ranger.webp",
    "heroAlt": "Ford Ranger For Sale",
    "sourceUrl": "https://www.vansales.com/product/ford-ranger-lease/",
    "sourceType": "product"
  },
  "mercedes-benz/sprinter": {
    "make": "Mercedes-Benz",
    "makeSlug": "mercedes-benz",
    "model": "Sprinter",
    "modelSlug": "sprinter",
    "title": "Mercedes-Benz Sprinter",
    "intro": [
      "I’ve created an image of a sleek white 2025 Mercedes Sprinter with “Vansales.com” displayed on the number plate, showcasing this impressive vehicle in a typical UK urban setting. See all Mercedes van lease deals",
      "Perfect for businesses needing to transport both personnel and equipment, the Crew Van features second-row seating while maintaining generous cargo space.",
      "The LCV market hit a four-year high in September 2024, with registrations up 8.3% compared to the previous year - Overall growth of 3.6% year-on-year represents the strongest performance since 2019 - This growth indicates increasing business confidence and investment in commercial vehicl",
      "Battery electric van (BEV) registrations declined for four consecutive months in late 2024 - Electric vans represented only 5.3% of the market, falling short of the UK’s 10% target - The government may need to extend incentives and improve infrastructure to encourage faster"
    ],
    "hero": "/media/models/mercedes-benz-sprinter.webp",
    "heroAlt": "Mercedes Sprinter For Sale",
    "sourceUrl": "https://www.vansales.com/product/mercedes-sprinter-lease/",
    "sourceType": "product"
  },
  "mercedes-benz/vito": {
    "make": "Mercedes-Benz",
    "makeSlug": "mercedes-benz",
    "model": "Vito",
    "modelSlug": "vito",
    "title": "Mercedes-Benz Vito",
    "intro": [
      "The Mercedes-Benz Vito is a refined mid-size van that drives like a car and works like a pro. It's a dependable choice for sole traders and fleets alike, balancing running costs, comfort and practicality for work across the UK.",
      "Browse Mercedes-Benz Vito vans for sale below from trusted UK dealers. Use the filters to narrow by price, year, wheelbase, body style and fuel, and check the ULEZ flag if you'll be working in a clean-air zone — every listing shows the full spec up front."
    ],
    "hero": "/media/models/mercedes-benz-vito.webp",
    "heroAlt": "Mercedes Vito For Sale",
    "sourceUrl": "",
    "sourceType": "generated"
  },
  "mercedes-benz/citan": {
    "make": "Mercedes-Benz",
    "makeSlug": "mercedes-benz",
    "model": "Citan",
    "modelSlug": "citan",
    "title": "Mercedes-Benz Citan",
    "intro": [
      "Our team spent six months testing both diesel and electric models during regular business operations. This hands-on experience helped us verify the claimed 54.3 mpg efficiency and 176-mile electric range. The diesel model caught our attention on urban routes with its 1.5-litre Euro 6d engine that produces 95 hp.",
      "This compact Mercedes proved its worth as we tested its expandable 1806 mm load length and measured actual fuel consumption under real-life conditions. Our detailed review will help you choose between the Progressive trim and Premium variant when you’re ready to lease a Mercedes Citan that fits your business needs.",
      "The Mercedes Citan caught our eye right away as we looked at small vans for our business fleet. It’s the smallest commercial vehicle in Mercedes-Benz’s range, fitting nicely below the mid-sized Vito and larger Sprinter.",
      "We thought long and hard before leasing a Mercedes Citan. The price tag was about £1,000 more than similar vans like the Renault Kangoo and Nissan Townstar. But several key features made this investment worth every penny for our business:"
    ],
    "hero": "/media/models/mercedes-benz-citan.webp",
    "heroAlt": "Mercedes Citan Lease",
    "sourceUrl": "https://www.vansales.com/product/mercedes-citan-lease/",
    "sourceType": "product"
  },
  "vauxhall/vivaro": {
    "make": "Vauxhall",
    "makeSlug": "vauxhall",
    "model": "Vivaro",
    "modelSlug": "vivaro",
    "title": "Vauxhall Vivaro",
    "intro": [
      "This van packs a powerful payload capacity of up to 1,458 kg and load volume of 6.6 m³. The range’s versatility shows in its two lengths and three weight categories. The electric model can travel up to 205 miles on a single charge.",
      "Our team spent six months putting various Vivaro models to the test. We focused on their real-life performance compared to the claimed 37.1 to 42.1 mpg fuel efficiency. Every aspect got our attention – from the 1.5-litre diesel engine options to the advanced driver assistance systems. This thorough testing helps you make a better leasing decision.",
      "This detailed review breaks down all essential information about running costs, performance and practicality. Our extensive testing gives you the facts you need to decide if a Vauxhall Vivaro lease deal fits your needs.",
      "You need to know which Vauxhall Vivaro lease model works best for your business needs. The latest Vivaro lineup makes choosing easier than older versions with its simplified model range."
    ],
    "hero": "/media/models/vauxhall-vivaro.webp",
    "heroAlt": "Vauxhall Vivaro For Sale",
    "sourceUrl": "https://www.vansales.com/product/vauxhall-vivaro-lease-2/",
    "sourceType": "product"
  },
  "vauxhall/combo": {
    "make": "Vauxhall",
    "makeSlug": "vauxhall",
    "model": "Combo",
    "modelSlug": "combo",
    "title": "Vauxhall Combo",
    "intro": [
      "Whether you’re a business owner looking for a dependable workhorse or a family seeking a spacious people carrier, understanding your leasing options is crucial. From flexible payment terms to various model configurations, finding affordable Vauxhall Combo lease deals requires careful consideration of multiple factors.",
      "This comprehensive guide breaks down everything you need to know about Vauxhall Combo leasing options, backed by real customer reviews and expert insights. We’ll help you navigate the choices available and find the perfect lease arrangement for your needs and budget.",
      "Before selecting a Vauxhall Combo lease, understanding the available models is essential to match your specific requirements. The Vauxhall Combo comes in various configurations designed for different business and personal needs.",
      "In contrast to the Panel Van’s focus on cargo, the Combo Life prioritizes passenger comfort with individual rear seating that includes three separate ISOFIX mounting points as standard for child seats 2. This family-friendly design has earned it recognition as the “Best Buy Car of Europe 2019” for offering exceptional value compared to competitors 2."
    ],
    "hero": "/media/models/vauxhall-combo.webp",
    "heroAlt": "Vauxhall Combo For Sale",
    "sourceUrl": "https://www.vansales.com/product/vauxhall-combi-lease/",
    "sourceType": "product"
  },
  "vauxhall/movano": {
    "make": "Vauxhall",
    "makeSlug": "vauxhall",
    "model": "Movano",
    "modelSlug": "movano",
    "title": "Vauxhall Movano",
    "intro": [
      "The Vauxhall Movano is a large panel van built for maximum load space and payload. It's a dependable choice for sole traders and fleets alike, balancing running costs, comfort and practicality for work across the UK.",
      "Browse Vauxhall Movano vans for sale below from trusted UK dealers. Use the filters to narrow by price, year, wheelbase, body style and fuel, and check the ULEZ flag if you'll be working in a clean-air zone — every listing shows the full spec up front."
    ],
    "hero": "/media/models/vauxhall-movano.webp",
    "heroAlt": "Vauxhall Movano For Sale",
    "sourceUrl": "",
    "sourceType": "generated"
  },
  "renault/master": {
    "make": "Renault",
    "makeSlug": "renault",
    "model": "Master",
    "modelSlug": "master",
    "title": "Renault Master",
    "intro": [
      "Specifically designed for commercial use, the Renault Master offers various configurations to match different business needs. However, navigating through leasing options, contract terms, and financial implications can feel overwhelming. This comprehensive guide breaks down everything you need to know about business van leasing for the Renault Master, from model specifications to contract options and practical tips for securing the best deal. See all Renault Van Lease Deals",
      "Commercial van leasing serves as a practical financing solution for businesses needing reliable transportation without the substantial upfront investment of purchasing. Understanding the basics of Renault Master leasing can help you make informed decisions that align with your business requirements and financial goals.",
      "Commercial van leasing represents a contractual arrangement where businesses pay fixed monthly amounts to use a vehicle for a predetermined period, typically ranging from two to five years. Unlike buying, you don’t own the vehicle but instead “rent” it for the duration of your lease term. This approach allows companies to access newer vehicles without committing to full ownership.",
      "The leasing company maintains legal title to the Renault Master throughout the agreement, while you gain equitable title – the right to use the vehicle and enjoy its financial benefits during the lease period. At the end of your lease, you generally have three options: return the vehicle, extend the lease, or purchase it at the pre-agreed residual value. See all Renault Master for sale"
    ],
    "hero": "/media/models/renault-master.webp",
    "heroAlt": "Renault Master For Sale",
    "sourceUrl": "https://www.vansales.com/product/renault-master-lease/",
    "sourceType": "product"
  },
  "renault/trafic": {
    "make": "Renault",
    "makeSlug": "renault",
    "model": "Trafic",
    "modelSlug": "trafic",
    "title": "Renault Trafic",
    "intro": [
      "Whether you’re running a small delivery service or managing a large fleet, getting the right vehicle at the right price is crucial for your bottom line. The Renault Trafic leasing option has become increasingly popular among smart business owners who want to maximize their budget while maintaining access to reliable transportation.",
      "In fact, commercial vehicle leasing offers significant advantages over traditional purchasing, from lower upfront costs to flexible terms that match your business needs. The Renault Trafic, with its impressive cargo capacity and fuel efficiency, stands out as a top choice for businesses seeking a dependable commercial van.",
      "This comprehensive guide will walk you through everything you need to know about Renault Trafic leasing – from various financing options and key features to potential pitfalls and money-saving tips. Let’s help you make an informed decision about your next commercial vehicle investment.",
      "The commercial vehicle market offers numerous acquisition methods for businesses of all sizes. Leasing has emerged as a particularly attractive option for those seeking operational flexibility."
    ],
    "hero": "/media/models/renault-trafic.webp",
    "heroAlt": "Renault Trafic For Sale",
    "sourceUrl": "https://www.vansales.com/product/renault-trafic-lease/",
    "sourceType": "product"
  },
  "renault/kangoo": {
    "make": "Renault",
    "makeSlug": "renault",
    "model": "Kangoo",
    "modelSlug": "kangoo",
    "title": "Renault Kangoo",
    "intro": [
      "Our six-month test period has shown why this vehicle attracts so much attention. The Kangoo’s payload capacity reaches up to 1000kg and load volumes extend to 4.2m³. These numbers make it a strong contender in its class. The vehicle comes with three powertrain choices – petrol, diesel, and an E-Tech electric version that runs for 186 miles on a single charge.",
      "Monthly payments start from £200.79 according to the brochure. Our long-term testing reveals the actual ownership costs and important details you should know. The real-life results from our testing will help you make a better decision if you’re thinking over a Kangoo for your business.",
      "Our Renault Kangoo lease van arrived, and we started a detailed 6-month evaluation. The van’s interior quality left a positive first impression that put it ahead of rivals like the Citroen Berlingo.",
      "The driver’s seat felt comfortable right away, though you can only adjust the steering wheel’s height. The 90hp 1.5-litre diesel engine packs enough punch for daily use, and you get maximum torque of 200Nm at 1750rpm. The five-speed manual gearbox responds well and shifts smoothly in city traffic."
    ],
    "hero": "/media/models/renault-kangoo.webp",
    "heroAlt": "Renault Kangoo For Sale",
    "sourceUrl": "https://www.vansales.com/product/renault-kangoo-lease/",
    "sourceType": "product"
  },
  "citroen/berlingo": {
    "make": "Citroën",
    "makeSlug": "citroen",
    "model": "Berlingo",
    "modelSlug": "berlingo",
    "title": "Citroën Berlingo",
    "intro": [
      "Looking for the right lease deal can feel overwhelming with so many options available. From various contract lengths to different mileage allowances, each choice affects your monthly payments and overall experience.",
      "While buying might seem like the obvious choice, leasing a Berlingo could actually save you money in the long run. You’ll get a brand-new vehicle with warranty coverage, predictable monthly costs, and the freedom to upgrade to a newer model when your contract ends.",
      "This comprehensive guide breaks down everything you need to know about Citroen Berlingo leasing options, helping you find the best deal for your needs. We’ll explore key features, compare different lease packages, and examine the financial benefits of choosing a Berlingo lease over purchase.",
      "Designed with versatility in mind, the Citroen Berlingo presents an impressive array of features that make it a compelling option for those considering a vehicle lease. From powerful engines to spacious interiors, this multi-purpose vehicle delivers practicality without compromising on performance or comfort."
    ],
    "hero": "/media/models/citroen-berlingo.png",
    "heroAlt": "Berlingo Van for Sale",
    "sourceUrl": "https://www.vansales.com/product/citroen-berlingo-lease/",
    "sourceType": "product"
  },
  "citroen/dispatch": {
    "make": "Citroën",
    "makeSlug": "citroen",
    "model": "Dispatch",
    "modelSlug": "dispatch",
    "title": "Citroën Dispatch",
    "intro": [
      "The van’s capabilities justify its competitive pricing. Diesel variants start at £283.60 monthly, while the e-Despatch costs £393.96 per month. The vehicle’s robust payload capacity reaches 1,446 kg and offers a generous maximum load volume of 6.6 m³. These features make it ideal for demanding business operations.",
      "Six months of rigorous business testing helped us evaluate the Despatch’s real-world performance. Our team conducted comprehensive assessments that included daily loading operations and fuel economy measurements. The results paint a clear picture of this versatile commercial vehicle’s capabilities.",
      "The Citroen Despatch Enterprise trim arrived, and its professional look caught my eye right away. The black front bumper, door handles and side protection strips gave it a clean, business-like appeal that our clients would love.",
      "Our new business lease setup turned out to be surprisingly easy. The handover came with complete documentation about the vehicle specs and lease terms. I worried about dealing with complex paperwork, but we finished everything in under an hour. The dealer walked me through our standard 36-month contract with our chosen 10,000 annual mileage allowance at £409 monthly (excluding VAT). On top of that, they explained the first payment of £2,454 and pointed out that road tax was included."
    ],
    "hero": "/media/models/citroen-dispatch.webp",
    "heroAlt": "Citroen Dispatch For Sale",
    "sourceUrl": "https://www.vansales.com/product/citroen-dispatch-lease/",
    "sourceType": "product"
  },
  "citroen/relay": {
    "make": "Citroën",
    "makeSlug": "citroen",
    "model": "Relay",
    "modelSlug": "relay",
    "title": "Citroën Relay",
    "intro": [
      "When searching for a large commercial vehicle, the Citroen Relay stands out as a versatile option that many UK businesses choose to lease rather than purchase outright. This comprehensive section explores what makes the Relay distinctive, why leasing might be advantageous, and how to decide between leasing and buying.",
      "The Citroen Relay is a large panel van designed for businesses requiring substantial cargo capacity and practical features. This versatile workhorse offers impressive load volumes of up to 17 cubic meters and can handle payloads reaching 1,870kg 1. Available in multiple configurations to suit various business needs, the Relay comes in four lengths, three heights, and with both diesel and electric powertrain options 2.",
      "Following its 2023 update, the Relay received a modern facelift improving its aerodynamics while introducing enhanced technology features 3. The current model offers impressive specifications including:",
      "Engine options: 2.2-liter diesel engines producing either 140 bhp or 180 bhp 3 - Electric e-Relay variant with 75kWh battery offering up to 154 miles range 4 - Best-in-class load width and low load sill height for easier loading/unloading 2 - Advanced technology including a 10-inch touchscreen and wireless phone charging on higher trims 3"
    ],
    "hero": "/media/models/citroen-relay.webp",
    "heroAlt": "Citroen Relay For Sale",
    "sourceUrl": "https://www.vansales.com/product/citroen-relay-lease/",
    "sourceType": "product"
  },
  "fiat/ducato": {
    "make": "Fiat",
    "makeSlug": "fiat",
    "model": "Ducato",
    "modelSlug": "ducato",
    "title": "Fiat Ducato",
    "intro": [
      "The Ducato’s pricing structure makes it available to most businesses, with monthly lease payments starting at £554.81 for the Ducato 35 Maxi L2. Businesses looking at lease options will appreciate the impressive payload capacity that ranges from 800kg to 2100kg. Lease deals come in many forms, from diesel models that deliver 36.2mpg to the all-electric E-Ducato that runs up to 175 miles on a single charge. My daily experience over six months has revealed some hidden costs and unexpected savings that you should know about. These vital details will help you make a smart decision before committing to a financial lease. See all vans for sale",
      "The Fiat Ducato serves as the life-blood of the commercial vehicle market. People celebrate it for its exceptional adaptability to business needs of all sizes. The original launch in 1981 marked the beginning of this flagship model that grew into Europe’s best-selling commercial vehicle. Its reputation stems from 40 years of state-of-the-art refinements. Businesses can think over more than 10,000 customization options while leasing their next vehicle. See all van leasing deals",
      "Delivery services benefit most from the Ducato’s squared load compartment design that streamlines parcel and goods transport. The van’s impressive carrying capacity makes it an attractive leasing option. Load volumes range from 10m³ up to 17m³ with payloads reaching up to 2.2 tons. Trade professionals appreciate the cabin’s comfortable workspace features such as: See all Fiat vans for sale",
      "The Ducato has become the preferred base for motorhome conversions. European manufacturers build all but one of these motorhomes on this platform. Many businesses choose Fiat Ducato financial lease arrangements over purchases because they can configure vehicles to match their exact operational needs. See all Fiat van leasing"
    ],
    "hero": "/media/models/fiat-ducato.webp",
    "heroAlt": "Fiat Ducato For Sale",
    "sourceUrl": "https://www.vansales.com/product/fiat-ducato-lease/",
    "sourceType": "product"
  },
  "fiat/doblo": {
    "make": "Fiat",
    "makeSlug": "fiat",
    "model": "Doblo",
    "modelSlug": "doblo",
    "title": "Fiat Doblo",
    "intro": [
      "This van stands out with its amazing versatility. You can choose between a 100HP diesel engine and a 136HP electric variant that covers 175 miles on a single charge. The Doblo’s practical design makes it a standout choice in Fiat’s van leasing lineup. Both short and long-wheelbase versions can handle up to 1,050kg of payload. See all Fiat doblo for sale",
      "My experience with this van spans every scenario you can imagine. From city deliveries to long-distance runs, I’ve tested all its features. The advanced safety systems and ground fuel consumption numbers tell the whole story. Anyone who wants to lease a Fiat Doblo for their business should read my complete, straight-talking review based on real experience. See all Fiat vans for sale",
      "I needed a versatile yet economical van for my delivery business. The Fiat Doblo caught my attention with its impressive mix of practicality and value.",
      "My delivery service needed a van with good cargo capacity that wouldn’t drain fuel. The vehicle had to handle tight urban streets while carrying different types of loads. The Fiat Doblo’s payload capacity of up to 1,050kg met these needs perfectly. The van’s Magic Cargo feature allowed up to 3.44m of load length, so I could transport longer items without switching to a bigger, less efficient vehicle."
    ],
    "hero": "/media/models/fiat-doblo.webp",
    "heroAlt": "Fiat Doblo For Sale",
    "sourceUrl": "https://www.vansales.com/product/fiat-doblo-lease/",
    "sourceType": "product"
  },
  "fiat/scudo": {
    "make": "Fiat",
    "makeSlug": "fiat",
    "model": "Scudo",
    "modelSlug": "scudo",
    "title": "Fiat Scudo",
    "intro": [
      "The Scudo lease deals come with both diesel and electric options. The diesel models run efficiently at 44.8 mpg, while the E-Scudo can travel 205 miles on a single charge. This makes it perfect for different business needs. The vehicle’s two length options of 4,950 mm and 5,300 mm, combined with its ‘Magic Cargo’ system, extend the loading area to 3.67 m. These features make the Scudo an excellent choice for businesses that need flexibility without stretching their budget.",
      "Businesses face a huge financial challenge when buying vans outright. A **Fiat Scudo lease** offers a better way that cuts down your original capital spending.",
      "A **fiat van lease** gives you the biggest advantage in upfront costs. Buying a new Fiat Scudo outright costs between £27,000 and £35,000 based on specifications. **Fiat scudo lease deals** need only an original rental payment that equals 3, 6, or 9 monthly payments.",
      "You can get a brand-new Fiat Scudo with just £778.98 as your first payment (based on a 3-month original rental). The money you save can go back into your core business operations and potentially earn more than what you spend on lease financing."
    ],
    "hero": "/media/models/fiat-scudo.webp",
    "heroAlt": "Fiat Scudo For Sale",
    "sourceUrl": "https://www.vansales.com/product/fiat-scudo-lease/",
    "sourceType": "product"
  },
  "peugeot/expert": {
    "make": "Peugeot",
    "makeSlug": "peugeot",
    "model": "Expert",
    "modelSlug": "expert",
    "title": "Peugeot Expert",
    "intro": [
      "A Peugeot van lease agreement needs careful thought, especially regarding usage beyond 20,000 miles. The monthly payment is just one factor to think over. The e-Expert’s two battery choices, various trim levels, and a £5,000 government grant make the decision more complex.",
      "Our 2025 analysis gives you a full picture of what it costs to lease a Peugeot Expert and where you can save money. This helps your business make the right choice.",
      "The Peugeot Expert 2025 lets you choose from several leasing options that match your business needs. A clear understanding of what comes with **peugeot expert lease deals** will help you make better financial decisions for your company.",
      "The 2025 Expert comes with two trim options – Professional and Asphalt. The Professional trim has simple features like black plastic bumpers, steel wheels, air conditioning, rear parking sensors, and the i-Cockpit infotainment system with digital instrument cluster. The Asphalt trim steps up with body-coloured bumpers and exterior trim. It also adds a reversing camera with separate digital rear-view mirror, blind spot monitoring and satellite navigation."
    ],
    "hero": "/media/models/peugeot-expert.webp",
    "heroAlt": "Peugeot Expert For Sale",
    "sourceUrl": "https://www.vansales.com/product/peugeot-expert-lease/",
    "sourceType": "product"
  },
  "peugeot/boxer": {
    "make": "Peugeot",
    "makeSlug": "peugeot",
    "model": "Boxer",
    "modelSlug": "boxer",
    "title": "Peugeot Boxer",
    "intro": [
      "Peugeot Boxer Finance Lease (secondary keyword): “A Peugeot Boxer finance lease allows businesses to spread the cost of the van over an agreed term while potentially benefiting from tax advantages.”",
      "Peugeot Boxer Business Lease (secondary keyword): “Opting for a Peugeot Boxer business lease can provide UK companies with a cost-effective way to access modern, reliable vans without the burden of ownership.”",
      "Each lease type has its advantages, and the best choice depends on factors such as your business’s financial situation, usage requirements, and long-term plans.",
      "Peugeot Boxer Lease Deals (secondary keyword): “Finding the right Peugeot Boxer lease deals can significantly impact your business’s bottom line and operational efficiency.”"
    ],
    "hero": "/media/models/peugeot-boxer.webp",
    "heroAlt": "Peugeot boxer for sale",
    "sourceUrl": "https://www.vansales.com/product/peugeot-boxer-lease/",
    "sourceType": "product"
  },
  "peugeot/partner": {
    "make": "Peugeot",
    "makeSlug": "peugeot",
    "model": "Partner",
    "modelSlug": "partner",
    "title": "Peugeot Partner",
    "intro": [
      "The Peugeot Partner is a compact, economical city van that's easy to live with. It's a dependable choice for sole traders and fleets alike, balancing running costs, comfort and practicality for work across the UK.",
      "Browse Peugeot Partner vans for sale below from trusted UK dealers. Use the filters to narrow by price, year, wheelbase, body style and fuel, and check the ULEZ flag if you'll be working in a clean-air zone — every listing shows the full spec up front."
    ],
    "hero": "/media/models/peugeot-partner.webp",
    "heroAlt": "Peugeot Partner Lease",
    "sourceUrl": "",
    "sourceType": "generated"
  },
  "toyota/proace": {
    "make": "Toyota",
    "makeSlug": "toyota",
    "model": "Proace",
    "modelSlug": "proace",
    "title": "Toyota Proace",
    "intro": [
      "Toyota Proace van leasing starts at £325.96 monthly and puts you behind the wheel of a feature-rich commercial vehicle. The van comes equipped with a 10-inch multimedia touchscreen and cutting-edge safety systems. More than 3,130 leasing offers are currently available. The electric model boasts an impressive 205-mile range. The Proace adapts to various business requirements while keeping operational costs in check.",
      "Ready to upgrade your commercial vehicle? Let’s take a closer look at what makes the Proace a smart investment and break down the actual costs of these lease deals.",
      "A **toyota proace lease** comes with two basic financing options. You can choose a full payout lease that runs between 24-60 months with fixed monthly payments. Balloon leases run for 24-48 months and let you push some of the cost to the end of the agreement, which reduces your monthly payments.",
      "Businesses can get great advantages from leasing beyond just convenience. VAT-registered companies using Business Contract Hire (BCH) can reclaim 50% of the VAT on monthly payments if they use the van for both business and personal trips. The VAT becomes 100% reclaimable if the vehicle serves only business purposes."
    ],
    "hero": "/media/models/toyota-proace.webp",
    "heroAlt": "Toyota Proace For Sale",
    "sourceUrl": "https://www.vansales.com/product/toyota-proace-lease-2/",
    "sourceType": "product"
  },
  "toyota/proace-city": {
    "make": "Toyota",
    "makeSlug": "toyota",
    "model": "Proace City",
    "modelSlug": "proace-city",
    "title": "Toyota Proace City",
    "intro": [
      "Let’s get into the actual costs and benefits of toyota proace lease deals to help you make a smart business choice in 2025.",
      "A toyota proace lease gives you several configuration options that help find the perfect match for your business needs. The Proace City has different body sizes, trim levels, and powertrain options that affect both capability and leasing costs.",
      "The Proace City comes in two body lengths – a short wheelbase (L1) at 4.4m and a long wheelbase (L2) at 4.7m. These size differences create meaningful capacity variations. The short model gives you 3.3-3.8 cubic metres of load space. The long version offers an impressive 3.9-4.4 cubic metres. The Smart Cargo system, standard on all 2024 models, extends load length to 3.1m for short wheelbase and 3.4m for long wheelbase variants.",
      "Each model’s payload capacity is different. The short wheelbase diesel carries up to 990kg, while the long version handles up to 950kg. Both sizes fit two Euro pallets – a feature you won’t find in all compact vans."
    ],
    "hero": "/media/models/toyota-proace-city.png",
    "heroAlt": "Toyota Proace City Lease",
    "sourceUrl": "https://www.vansales.com/product/toyota-proace-city-lease/",
    "sourceType": "product"
  },
  "toyota/hilux": {
    "make": "Toyota",
    "makeSlug": "toyota",
    "model": "Hilux",
    "modelSlug": "hilux",
    "title": "Toyota Hilux",
    "intro": [
      "Monthly lease payments start from £331.85 and go up to £537.40 – an attractive range that catches many eyes. The vehicle packs quite a punch with its mighty 3.5-tonne towing capacity and can carry over 1,000kg. This workhorse delivers impressive value for your investment.",
      "My experience analysing countless lease deals tells me there’s more to the story than advertised prices. Let me help you discover the hidden costs, potential savings, and everything in leasing a Hilux that most drivers miss.",
      "The advertised monthly rate isn’t the whole story when you look at a Toyota Hilux lease agreement. Your actual payments throughout the contract term depend on several cost components.",
      "The 2025 Toyota Hilux comes in different trim levels with varying monthly payments. A 4-year contract with 10,000 annual miles starts at £331.85 per month for the Active trim. The Icon trim costs about £382.45 monthly. The premium models cost more – Invincible runs £473.19 while Invincible X tops out at £537.40."
    ],
    "hero": "/media/models/toyota-hilux.webp",
    "heroAlt": "Toyota Hilux for sale",
    "sourceUrl": "https://www.vansales.com/product/toyota-hilux-lease/",
    "sourceType": "product"
  },
  "nissan/townstar": {
    "make": "Nissan",
    "makeSlug": "nissan",
    "model": "Townstar",
    "modelSlug": "townstar",
    "title": "Nissan Townstar",
    "intro": [
      "The process of selecting from different Townstar configurations and lease options can feel overwhelming. Our review breaks down the actual costs and uncovers potential savings. We’ll help you determine if a Nissan Townstar lease fits your budget and business needs perfectly.",
      "A clear understanding of cost structure helps you make smart decisions about your Nissan Townstar lease. The lease packages start with an upfront payment and continue with fixed monthly payments throughout the contract.",
      "The Nissan Townstar L1 petrol Acenta model’s business lease deals start at £261.84 monthly with an upfront payment of £3,142.08. This applies to a 48-month contract with 10,000 annual miles. You can also opt for shorter 24-month contracts at £297.93 monthly with a £3,575.16 upfront payment.",
      "The L1 EV Acenta electric model costs more, starting at £387.35 monthly on a 60-month contract with a £4,648.20 upfront payment. These electric models match their petrol counterparts with an 800kg payload capacity."
    ],
    "hero": "/media/models/nissan-townstar.webp",
    "heroAlt": "Nissan Townstar",
    "sourceUrl": "https://www.vansales.com/product/nissan-townstar-lease/",
    "sourceType": "product"
  },
  "nissan/interstar": {
    "make": "Nissan",
    "makeSlug": "nissan",
    "model": "Interstar",
    "modelSlug": "interstar",
    "title": "Nissan Interstar",
    "intro": [
      "A powerful 2.3 dCi 145ps engine powers this tipper, and it comes with stop/start technology that balances strength and efficiency. On top of that, its 3500 kg towing capacity delivers practical solutions for tough jobs. The spacious cargo area measures 3205 mm in length and 2100 mm in width.",
      "We’ve really put this £32,995 workhorse through its paces. The vehicle comes with a 5-year warranty and detailed roadside assistance package. Nissan has clearly built this tipper with reliability in mind. Let’s get into whether this tipper lives up to its promising specs.",
      "The 2025 Nissan Interstar Tipper is a strong commercial vehicle built for heavy-duty work. This tipper model comes with an electronically powered load deck that automatically tilts at a 45° angle, making material unloading quick and easy.",
      "A powerful and efficient diesel engine sits at this Nissan Interstar Tipper’s core. The vehicle has Euro 6D-compliant engines that meet current emission standards and deliver great performance. The 130 BHP option gives users the perfect mix of power and fuel economy, even though engine options vary across different models."
    ],
    "hero": "/media/models/nissan-interstar.webp",
    "heroAlt": "Nissan Interstar Lease",
    "sourceUrl": "https://www.vansales.com/product/nissan-interstar-tipper/",
    "sourceType": "product"
  },
  "nissan/primastar": {
    "make": "Nissan",
    "makeSlug": "nissan",
    "model": "Primastar",
    "modelSlug": "primastar",
    "title": "Nissan Primastar",
    "intro": [
      "The Nissan Primastar is a versatile medium panel van suited to everyday trade work. It's a dependable choice for sole traders and fleets alike, balancing running costs, comfort and practicality for work across the UK.",
      "Browse Nissan Primastar vans for sale below from trusted UK dealers. Use the filters to narrow by price, year, wheelbase, body style and fuel, and check the ULEZ flag if you'll be working in a clean-air zone — every listing shows the full spec up front."
    ],
    "hero": "/media/models/nissan-primastar.webp",
    "heroAlt": "Nissan Primastar",
    "sourceUrl": "",
    "sourceType": "generated"
  },
  "iveco/daily": {
    "make": "Iveco",
    "makeSlug": "iveco",
    "model": "Daily",
    "modelSlug": "daily",
    "title": "Iveco Daily",
    "intro": [
      "The Iveco Daily combines outstanding capability with smart features. Its spacious design offers a maximum load volume of 19.6 cubic metres and comes equipped with advanced driver assistance systems. The van’s proven reliability and powerful 3,500 kg towing capacity make it an excellent choice for businesses. This piece will help you understand what you need to know about finding the right Iveco Daily van lease that fits your business requirements.",
      "Businesses can save money and gain flexibility by leasing an Iveco Daily instead of buying one outright. You can rent the vehicle for a set time and make monthly payments rather than owning it completely.",
      "You’ll find two main options for leasing an Iveco van. The Operating Lease keeps the vehicle under Iveco Capital’s ownership as an off-balance-sheet item. Your monthly payments will be lower because the vehicle’s residual value plays a role in the deal. The Finance Lease lets you hire the vehicle without spending capital that could affect your cash flow and balance sheet. This agreement gives you choices at the end – you can keep renting for a small fee or help sell the vehicle.",
      "The monthly cost of an Iveco Daily van lease starts at £882.32 for businesses. You can choose upfront payments ranging from 1 to 12 months. Contracts run between 12 and 60 months, and yearly mileage starts as low as 5,000 miles."
    ],
    "hero": "/media/models/iveco-daily.webp",
    "heroAlt": "Iveco Daily Luton For Sale",
    "sourceUrl": "https://www.vansales.com/product/iveco-daily-lease/",
    "sourceType": "product"
  }
};

export function getModelContent(makeSlug: string, modelSlug: string): ModelContent | null {
  return MODEL_CONTENT[`${makeSlug}/${modelSlug}`] ?? null;
}

/** Hero image path for a make/model, or null. Keyed leniently for feed lookups. */
export function modelImage(makeSlug: string, modelSlug: string): string | null {
  return MODEL_CONTENT[`${makeSlug}/${modelSlug}`]?.hero ?? null;
}
