// AUTO-GENERATED by scripts/generate-model-images.mjs — do not edit by hand.
// Curated per-model image sets from the read-only vansales.com harvest.
// Hard-filtered: no logos/icons/banners/tiny/odd-aspect; spam-checked alts.

export interface ModelImage {
  src: string;
  alt: string;
  fit: "cover" | "contain"; // cover = real photo; contain = studio cutout on a surface
  w: number;
  h: number;
}

export const MODEL_IMAGE_SETS: Record<string, ModelImage[]> = {
  "volkswagen/transporter": [
    {
      "src": "/media/models/volkswagen/transporter/1.png",
      "alt": "VW transporter Dimensions",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/volkswagen/transporter/2.png",
      "alt": "VW Transporter Sportline Black Edition for Sale Today",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/volkswagen/transporter/3.webp",
      "alt": "VW Transporter",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/transporter/4.webp",
      "alt": "VW Transporter For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/transporter/5.jpg",
      "alt": "Volkswagen Transporter: The Reliable Companion",
      "fit": "cover",
      "w": 1024,
      "h": 576
    },
    {
      "src": "/media/models/volkswagen/transporter/6.webp",
      "alt": "VW Transporter T7",
      "fit": "cover",
      "w": 600,
      "h": 600
    }
  ],
  "volkswagen/transporter-kombi": [
    {
      "src": "/media/models/volkswagen/transporter-kombi/1.webp",
      "alt": "VW Transporter Kombi",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/transporter-kombi/2.webp",
      "alt": "VW Transporter Kombi",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/transporter-kombi/3.webp",
      "alt": "Ford Transit Custom Kombi Lease",
      "fit": "cover",
      "w": 1330,
      "h": 848
    },
    {
      "src": "/media/models/volkswagen/transporter-kombi/4.webp",
      "alt": "VW Transporter Kombi Lease",
      "fit": "contain",
      "w": 700,
      "h": 503
    }
  ],
  "volkswagen/caddy": [
    {
      "src": "/media/models/volkswagen/caddy/1.webp",
      "alt": "VW Caddy",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/caddy/2.webp",
      "alt": "VW Caddy",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/caddy/3.webp",
      "alt": "VW Caddy Lease",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/volkswagen/caddy/4.webp",
      "alt": "VW Caddy",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/caddy/5.webp",
      "alt": "VW Caddy For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/caddy/6.webp",
      "alt": "VW Caddy",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "volkswagen/crafter": [
    {
      "src": "/media/models/volkswagen/crafter/1.png",
      "alt": "VW Crafter Dimensions",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/volkswagen/crafter/2.jpg",
      "alt": "VW Crafter Conversion",
      "fit": "cover",
      "w": 900,
      "h": 514
    },
    {
      "src": "/media/models/volkswagen/crafter/3.jpg",
      "alt": "Crafter luton tail lift",
      "fit": "cover",
      "w": 1280,
      "h": 853
    },
    {
      "src": "/media/models/volkswagen/crafter/4.webp",
      "alt": "VW Crafter Luton",
      "fit": "cover",
      "w": 1920,
      "h": 1281
    },
    {
      "src": "/media/models/volkswagen/crafter/5.webp",
      "alt": "VW Crafter For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/crafter/6.webp",
      "alt": "VW Crafter Tipper",
      "fit": "cover",
      "w": 600,
      "h": 600
    }
  ],
  "volkswagen/amarok": [
    {
      "src": "/media/models/volkswagen/amarok/1.webp",
      "alt": "VW Amarok For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/amarok/2.webp",
      "alt": "VW Amarok Aventura",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/volkswagen/amarok/3.webp",
      "alt": "VW Amarok Lease",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/volkswagen/amarok/4.webp",
      "alt": "VW Amarok",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/volkswagen/amarok/5.webp",
      "alt": "VW Amarok Pan America",
      "fit": "cover",
      "w": 600,
      "h": 376
    },
    {
      "src": "/media/models/volkswagen/amarok/6.webp",
      "alt": "VW Amarok Life",
      "fit": "cover",
      "w": 600,
      "h": 382
    }
  ],
  "ford/transit-custom": [
    {
      "src": "/media/models/ford/transit-custom/1.webp",
      "alt": "Ford Transit Custom Sport Finance",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/transit-custom/2.webp",
      "alt": "2024 Ford Transit Custom Sport: What's New and Improved?",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/transit-custom/3.webp",
      "alt": "Customizing Your Ford Transit Custom Sport",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/transit-custom/4.webp",
      "alt": "Ford Transit Custom Interior",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/transit-custom/5.png",
      "alt": "Ford Transit Custom Dimensions",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/ford/transit-custom/6.webp",
      "alt": "ford transit custom sport colors",
      "fit": "cover",
      "w": 1344,
      "h": 768
    }
  ],
  "ford/transit": [
    {
      "src": "/media/models/ford/transit/1.jpg",
      "alt": "Ford Transit 350: The Practical Choice",
      "fit": "cover",
      "w": 1024,
      "h": 576
    },
    {
      "src": "/media/models/ford/transit/2.webp",
      "alt": "Ford Transit Luton",
      "fit": "cover",
      "w": 1000,
      "h": 670
    },
    {
      "src": "/media/models/ford/transit/3.webp",
      "alt": "Ford Transit Tipper",
      "fit": "cover",
      "w": 700,
      "h": 350
    },
    {
      "src": "/media/models/ford/transit/4.webp",
      "alt": "Ford Transit Tipper",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/ford/transit/5.webp",
      "alt": "Ford Transit",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit/6.webp",
      "alt": "Ford Transit Double Cab Lease",
      "fit": "cover",
      "w": 700,
      "h": 527
    }
  ],
  "ford/transit-connect": [
    {
      "src": "/media/models/ford/transit-connect/1.webp",
      "alt": "New 2024 Ford Transit Connect",
      "fit": "cover",
      "w": 1720,
      "h": 982
    },
    {
      "src": "/media/models/ford/transit-connect/2.jpg",
      "alt": "New Ford Transit Connect",
      "fit": "cover",
      "w": 868,
      "h": 620
    },
    {
      "src": "/media/models/ford/transit-connect/3.webp",
      "alt": "Ford Transit Connect",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit-connect/4.webp",
      "alt": "Ford Connect Vans For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit-connect/5.webp",
      "alt": "Ford Connect",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit-connect/6.png",
      "alt": "Ford Transit Connect Lease",
      "fit": "contain",
      "w": 581,
      "h": 337
    }
  ],
  "ford/transit-courier": [
    {
      "src": "/media/models/ford/transit-courier/1.jpg",
      "alt": "New Ford Courier Van",
      "fit": "cover",
      "w": 624,
      "h": 428
    },
    {
      "src": "/media/models/ford/transit-courier/2.webp",
      "alt": "Ford Transit Courier",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit-courier/3.webp",
      "alt": "Ford Transit Custom Courier",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/ford/transit-courier/4.webp",
      "alt": "Ford Courier Lease",
      "fit": "cover",
      "w": 500,
      "h": 378
    },
    {
      "src": "/media/models/ford/transit-courier/5.webp",
      "alt": "Ford Courier Lease",
      "fit": "cover",
      "w": 500,
      "h": 318
    },
    {
      "src": "/media/models/ford/transit-courier/6.webp",
      "alt": "Ford Transit Custom Courier",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "ford/ranger": [
    {
      "src": "/media/models/ford/ranger/1.jpg",
      "alt": "Ford Ranger Accessories",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/ranger/2.webp",
      "alt": "Top Ford Ranger Canopy Options for Your Wildtrak",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/ranger/3.webp",
      "alt": "Ford Ranger Raptor:",
      "fit": "cover",
      "w": 1344,
      "h": 768
    },
    {
      "src": "/media/models/ford/ranger/4.webp",
      "alt": "Ford Ranger PHEV",
      "fit": "cover",
      "w": 900,
      "h": 514
    },
    {
      "src": "/media/models/ford/ranger/5.webp",
      "alt": "Ford Ranger Raptor Lease",
      "fit": "cover",
      "w": 700,
      "h": 489
    },
    {
      "src": "/media/models/ford/ranger/6.webp",
      "alt": "Ford Ranger For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "mercedes-benz/sprinter": [
    {
      "src": "/media/models/mercedes-benz/sprinter/1.webp",
      "alt": "Mercedes E SprinterLease",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/mercedes-benz/sprinter/2.webp",
      "alt": "Mercedes Sprinter Luton",
      "fit": "cover",
      "w": 512,
      "h": 383
    },
    {
      "src": "/media/models/mercedes-benz/sprinter/3.webp",
      "alt": "Mercedes Sprinter Dropside",
      "fit": "cover",
      "w": 600,
      "h": 356
    },
    {
      "src": "/media/models/mercedes-benz/sprinter/4.webp",
      "alt": "Mercedes Sprinter Tipper",
      "fit": "contain",
      "w": 1024,
      "h": 1024
    },
    {
      "src": "/media/models/mercedes-benz/sprinter/5.webp",
      "alt": "Mercedes Sprinter Tipper",
      "fit": "contain",
      "w": 1024,
      "h": 1024
    },
    {
      "src": "/media/models/mercedes-benz/sprinter/6.webp",
      "alt": "Mercedes Sprinter Tipper",
      "fit": "contain",
      "w": 947,
      "h": 546
    }
  ],
  "mercedes-benz/vito": [
    {
      "src": "/media/models/mercedes-benz/vito/1.webp",
      "alt": "Mercedes Vito 9 Seater",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/mercedes-benz/vito/2.webp",
      "alt": "Mercedes Vito",
      "fit": "cover",
      "w": 600,
      "h": 600
    },
    {
      "src": "/media/models/mercedes-benz/vito/3.webp",
      "alt": "Mercedes Vito Tourer Lease",
      "fit": "cover",
      "w": 500,
      "h": 339
    },
    {
      "src": "/media/models/mercedes-benz/vito/4.webp",
      "alt": "Mercedes vito crew cab",
      "fit": "cover",
      "w": 600,
      "h": 338
    },
    {
      "src": "/media/models/mercedes-benz/vito/5.webp",
      "alt": "Mercedes Vito Lease",
      "fit": "cover",
      "w": 600,
      "h": 338
    }
  ],
  "mercedes-benz/citan": [
    {
      "src": "/media/models/mercedes-benz/citan/1.webp",
      "alt": "Mercedes Citan Lease",
      "fit": "cover",
      "w": 586,
      "h": 306
    },
    {
      "src": "/media/models/mercedes-benz/citan/2.webp",
      "alt": "Mercedes Citan Lease",
      "fit": "cover",
      "w": 600,
      "h": 420
    }
  ],
  "vauxhall/vivaro": [
    {
      "src": "/media/models/vauxhall/vivaro/1.webp",
      "alt": "Vauxhall Vivaro",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/vauxhall/vivaro/2.webp",
      "alt": "Vauxhall Vivaro Lease Deals",
      "fit": "cover",
      "w": 500,
      "h": 365
    }
  ],
  "vauxhall/combo": [
    {
      "src": "/media/models/vauxhall/combo/1.webp",
      "alt": "Vauxhall Combo",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/vauxhall/combo/2.webp",
      "alt": "Vauxhall Combo",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "vauxhall/movano": [
    {
      "src": "/media/models/vauxhall/movano/1.webp",
      "alt": "Vauxhall Movano Lease",
      "fit": "cover",
      "w": 500,
      "h": 324
    }
  ],
  "renault/master": [
    {
      "src": "/media/models/renault/master/1.webp",
      "alt": "Renault Master",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/master/2.webp",
      "alt": "Nissan Primaster",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/master/3.webp",
      "alt": "Renault Master",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/master/4.webp",
      "alt": "New Renault Master",
      "fit": "cover",
      "w": 700,
      "h": 394
    },
    {
      "src": "/media/models/renault/master/5.webp",
      "alt": "Renault Master Lease",
      "fit": "cover",
      "w": 500,
      "h": 344
    },
    {
      "src": "/media/models/renault/master/6.webp",
      "alt": "Renault Master Luton",
      "fit": "contain",
      "w": 700,
      "h": 700
    }
  ],
  "renault/trafic": [
    {
      "src": "/media/models/renault/trafic/1.webp",
      "alt": "Renault Trafic",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/trafic/2.webp",
      "alt": "Renault Trafic",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/trafic/3.jpg",
      "alt": "Renault Trafic LL30: The Versatile Van",
      "fit": "cover",
      "w": 1024,
      "h": 576
    },
    {
      "src": "/media/models/renault/trafic/4.webp",
      "alt": "renault trafic blue",
      "fit": "cover",
      "w": 600,
      "h": 367
    },
    {
      "src": "/media/models/renault/trafic/5.webp",
      "alt": "LWB Renault Trafic SPort",
      "fit": "cover",
      "w": 500,
      "h": 333
    },
    {
      "src": "/media/models/renault/trafic/6.webp",
      "alt": "Renault Trafic",
      "fit": "cover",
      "w": 700,
      "h": 394
    }
  ],
  "renault/kangoo": [
    {
      "src": "/media/models/renault/kangoo/1.webp",
      "alt": "Renault Kangoo For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/renault/kangoo/2.webp",
      "alt": "Renault Kangoo",
      "fit": "cover",
      "w": 700,
      "h": 466
    },
    {
      "src": "/media/models/renault/kangoo/3.webp",
      "alt": "Renault Kangoo Electric",
      "fit": "cover",
      "w": 1214,
      "h": 726
    },
    {
      "src": "/media/models/renault/kangoo/4.webp",
      "alt": "Renault Kangoo",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/renault/kangoo/5.webp",
      "alt": "Renault Kangoo Lease",
      "fit": "cover",
      "w": 500,
      "h": 337
    },
    {
      "src": "/media/models/renault/kangoo/6.webp",
      "alt": "Renault Kangoo Lease",
      "fit": "contain",
      "w": 583,
      "h": 335
    }
  ],
  "citroen/berlingo": [
    {
      "src": "/media/models/citroen/berlingo/1.webp",
      "alt": "Citroen Berlingo For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/berlingo/2.webp",
      "alt": "Citroen Berlingo",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/berlingo/3.webp",
      "alt": "Citroen Berlingo For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/berlingo/4.webp",
      "alt": "Citroen Berlingo Crew Cab",
      "fit": "cover",
      "w": 594,
      "h": 299
    },
    {
      "src": "/media/models/citroen/berlingo/5.webp",
      "alt": "Citroen Berlingo Lease Deals",
      "fit": "cover",
      "w": 500,
      "h": 309
    },
    {
      "src": "/media/models/citroen/berlingo/6.webp",
      "alt": "Citroen Berlingo Lease",
      "fit": "cover",
      "w": 651,
      "h": 336
    }
  ],
  "citroen/dispatch": [
    {
      "src": "/media/models/citroen/dispatch/1.webp",
      "alt": "Citroen Dispatch For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/dispatch/2.webp",
      "alt": "Citroen Dispatch Crew Cab",
      "fit": "cover",
      "w": 770,
      "h": 490
    },
    {
      "src": "/media/models/citroen/dispatch/3.webp",
      "alt": "Citroen E Dispatch",
      "fit": "cover",
      "w": 600,
      "h": 345
    },
    {
      "src": "/media/models/citroen/dispatch/4.webp",
      "alt": "Citroen Dispatch For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "citroen/relay": [
    {
      "src": "/media/models/citroen/relay/1.webp",
      "alt": "Citroen E Relay",
      "fit": "cover",
      "w": 700,
      "h": 574
    },
    {
      "src": "/media/models/citroen/relay/2.webp",
      "alt": "Citroen Relay For Sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/relay/3.webp",
      "alt": "Citroen Relay",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/relay/4.webp",
      "alt": "Citroen Relay Tipper",
      "fit": "cover",
      "w": 700,
      "h": 394
    },
    {
      "src": "/media/models/citroen/relay/5.webp",
      "alt": "Citroen Relay",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/citroen/relay/6.webp",
      "alt": "Citroen Relay Lease",
      "fit": "cover",
      "w": 700,
      "h": 388
    }
  ],
  "fiat/ducato": [
    {
      "src": "/media/models/fiat/ducato/1.webp",
      "alt": "Fiat E Ducato",
      "fit": "cover",
      "w": 500,
      "h": 354
    },
    {
      "src": "/media/models/fiat/ducato/2.webp",
      "alt": "Fiat Ducato Lease",
      "fit": "cover",
      "w": 671,
      "h": 352
    },
    {
      "src": "/media/models/fiat/ducato/3.webp",
      "alt": "Fiat Ducato Lease Deals",
      "fit": "cover",
      "w": 500,
      "h": 320
    },
    {
      "src": "/media/models/fiat/ducato/4.webp",
      "alt": "Fiat Ducato Lease",
      "fit": "cover",
      "w": 500,
      "h": 282
    },
    {
      "src": "/media/models/fiat/ducato/5.webp",
      "alt": "Fiat Ducato Luton",
      "fit": "contain",
      "w": 595,
      "h": 447
    },
    {
      "src": "/media/models/fiat/ducato/6.webp",
      "alt": "Fiat Ducato Luton",
      "fit": "contain",
      "w": 700,
      "h": 700
    }
  ],
  "fiat/doblo": [
    {
      "src": "/media/models/fiat/doblo/1.webp",
      "alt": "Fiat Doblo Lease",
      "fit": "cover",
      "w": 700,
      "h": 412
    },
    {
      "src": "/media/models/fiat/doblo/2.webp",
      "alt": "Fiat Doblo Lease Deals",
      "fit": "cover",
      "w": 500,
      "h": 416
    },
    {
      "src": "/media/models/fiat/doblo/3.webp",
      "alt": "Fiat E Doblo",
      "fit": "cover",
      "w": 500,
      "h": 287
    },
    {
      "src": "/media/models/fiat/doblo/4.webp",
      "alt": "Fiat Doblo Side",
      "fit": "contain",
      "w": 700,
      "h": 372
    }
  ],
  "fiat/scudo": [
    {
      "src": "/media/models/fiat/scudo/1.webp",
      "alt": "Fiat Scudo Crew Van",
      "fit": "cover",
      "w": 600,
      "h": 440
    },
    {
      "src": "/media/models/fiat/scudo/2.webp",
      "alt": "Fiat Scudo Lease",
      "fit": "cover",
      "w": 500,
      "h": 320
    },
    {
      "src": "/media/models/fiat/scudo/3.webp",
      "alt": "Fiat Scudo Lease",
      "fit": "cover",
      "w": 500,
      "h": 308
    }
  ],
  "peugeot/expert": [
    {
      "src": "/media/models/peugeot/expert/1.webp",
      "alt": "Peugeot Expert Lease",
      "fit": "cover",
      "w": 600,
      "h": 390
    },
    {
      "src": "/media/models/peugeot/expert/2.webp",
      "alt": "Peugeot Expert For Sale",
      "fit": "cover",
      "w": 700,
      "h": 400
    },
    {
      "src": "/media/models/peugeot/expert/3.webp",
      "alt": "Peugeot Expert Lease",
      "fit": "cover",
      "w": 491,
      "h": 243
    }
  ],
  "peugeot/boxer": [
    {
      "src": "/media/models/peugeot/boxer/1.webp",
      "alt": "Peugeot boxer for sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/peugeot/boxer/2.webp",
      "alt": "Peugeot Boxer Lease",
      "fit": "cover",
      "w": 667,
      "h": 380
    },
    {
      "src": "/media/models/peugeot/boxer/3.webp",
      "alt": "Peugeot Boxer Lease",
      "fit": "cover",
      "w": 500,
      "h": 477
    }
  ],
  "peugeot/partner": [
    {
      "src": "/media/models/peugeot/partner/1.webp",
      "alt": "Peugeot Partner Lease",
      "fit": "cover",
      "w": 500,
      "h": 501
    },
    {
      "src": "/media/models/peugeot/partner/2.webp",
      "alt": "Peugeot Partner Lease",
      "fit": "contain",
      "w": 603,
      "h": 323
    },
    {
      "src": "/media/models/peugeot/partner/3.webp",
      "alt": "Peugeot Partner",
      "fit": "contain",
      "w": 700,
      "h": 414
    }
  ],
  "toyota/proace": [
    {
      "src": "/media/models/toyota/proace/1.webp",
      "alt": "Toyota Proace",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/toyota/proace/2.webp",
      "alt": "Toyota Proace",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/toyota/proace/3.webp",
      "alt": "Toyota Proace Lease Deals",
      "fit": "cover",
      "w": 600,
      "h": 457
    },
    {
      "src": "/media/models/toyota/proace/4.png",
      "alt": "Toyota Proace Lease",
      "fit": "contain",
      "w": 867,
      "h": 354
    },
    {
      "src": "/media/models/toyota/proace/5.webp",
      "alt": "Toyota Proace Crew Cab",
      "fit": "contain",
      "w": 1130,
      "h": 625
    },
    {
      "src": "/media/models/toyota/proace/6.webp",
      "alt": "Toyota Proace Sport",
      "fit": "contain",
      "w": 700,
      "h": 360
    }
  ],
  "toyota/proace-city": [
    {
      "src": "/media/models/toyota/proace-city/1.png",
      "alt": "Toyota Proace City Lease",
      "fit": "contain",
      "w": 680,
      "h": 444
    },
    {
      "src": "/media/models/toyota/proace-city/2.png",
      "alt": "Toyota Proace City",
      "fit": "contain",
      "w": 867,
      "h": 354
    },
    {
      "src": "/media/models/toyota/proace-city/3.png",
      "alt": "Toyota Proace City",
      "fit": "contain",
      "w": 867,
      "h": 354
    },
    {
      "src": "/media/models/toyota/proace-city/4.png",
      "alt": "Toyota Proace City",
      "fit": "contain",
      "w": 867,
      "h": 354
    },
    {
      "src": "/media/models/toyota/proace-city/5.png",
      "alt": "Toyota Proace City",
      "fit": "contain",
      "w": 867,
      "h": 354
    }
  ],
  "toyota/hilux": [
    {
      "src": "/media/models/toyota/hilux/1.png",
      "alt": "Toyota Hilux Lease",
      "fit": "cover",
      "w": 600,
      "h": 351
    },
    {
      "src": "/media/models/toyota/hilux/2.webp",
      "alt": "Toyota Hilux for sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/toyota/hilux/3.webp",
      "alt": "Toyota Hilux",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/toyota/hilux/4.webp",
      "alt": "Toyota Hilux for sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/toyota/hilux/5.webp",
      "alt": "Toyota Hilux for sale",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "nissan/townstar": [
    {
      "src": "/media/models/nissan/townstar/1.webp",
      "alt": "Nissan Townstar Lease",
      "fit": "cover",
      "w": 527,
      "h": 306
    },
    {
      "src": "/media/models/nissan/townstar/2.webp",
      "alt": "Nissan Townstar",
      "fit": "contain",
      "w": 700,
      "h": 415
    }
  ],
  "nissan/interstar": [
    {
      "src": "/media/models/nissan/interstar/1.webp",
      "alt": "Nissan Interstar",
      "fit": "cover",
      "w": 700,
      "h": 700
    },
    {
      "src": "/media/models/nissan/interstar/2.webp",
      "alt": "Nissan Interstar",
      "fit": "cover",
      "w": 700,
      "h": 700
    }
  ],
  "nissan/primastar": [
    {
      "src": "/media/models/nissan/primastar/1.webp",
      "alt": "Nissan Primastar",
      "fit": "contain",
      "w": 700,
      "h": 467
    }
  ],
  "iveco/daily": [
    {
      "src": "/media/models/iveco/daily/1.webp",
      "alt": "Iveco Daily Luton Van",
      "fit": "cover",
      "w": 1600,
      "h": 960
    },
    {
      "src": "/media/models/iveco/daily/2.webp",
      "alt": "Iveco Daily Tipper",
      "fit": "cover",
      "w": 670,
      "h": 415
    },
    {
      "src": "/media/models/iveco/daily/3.webp",
      "alt": "Electric Iveco Daily",
      "fit": "cover",
      "w": 600,
      "h": 484
    },
    {
      "src": "/media/models/iveco/daily/4.webp",
      "alt": "Iveco Daily 4x4 Panel van",
      "fit": "cover",
      "w": 600,
      "h": 453
    },
    {
      "src": "/media/models/iveco/daily/5.webp",
      "alt": "Iveco Daily Luton For Sale",
      "fit": "cover",
      "w": 500,
      "h": 350
    },
    {
      "src": "/media/models/iveco/daily/6.webp",
      "alt": "Iveco Daily Lease Deals",
      "fit": "cover",
      "w": 500,
      "h": 388
    }
  ]
};
